### ISSUE TITLE
Some fonts not available in CSS

### ISSUE THREAD

**Issue by TimGeisler** [db-ui/core#17]
There are some fonts in https://github.com/db-ui/base/tree/main/assets/fonts (dbscreenhead-regular, dbscreensans-medium, dbscreensans-semibold, ...) which are not converted to CSS definitions of those fonts (see https://github.com/db-ui/core/blob/main/source/_patterns/00-base/type/_fonts.variables.scss).

Is there a reason for this mismatch?

**Comment by mfranzke** [comment]
@TimGeisler thanks a lot for your question.
It's mainly related to that with DB UI Base we'd like to provide all of the font assets that are downloadable by the [DB Marketingportal](https://marketingportal.extranet.deutschebahn.com/), but DB UI Core is based on the DB UX Design System (which is hosted at the [UI Components website on the Marketingportal](https://marketingportal.extranet.deutschebahn.com/de/ui-komponenten) as well). Within this DB UX Design System only a smaller amount of fonts is being used and that for only those are provided as `@font-face` declarations by DB UI Core.

Still it might be a good idea to at least provide some further font faces for in-between `font-weight`s – I'll align this with our creative colleagues and come back to your request.
