### ISSUE TITLE
broken navigation in documentation for icons

### ISSUE THREAD

**Issue by pschaub** [db-ui/core#367]
The navigation for icons in the documentation is broken.

## Reproduction
1. Open https://db-ui.github.io/core/?p=viewall-base-icons
2. See broken navigation on the left side.

**Comment by mfranzke** [comment]
@pschaub that's sadly a known bug out of the tool we're using – I've opened a ticket and PR to get this solved:
https://github.com/pattern-lab/patternlab-node/issues/1491
