### ISSUE TITLE
Inputs and Selects have different margin

### ISSUE THREAD

**Issue by juthilo** [db-ui/core#391]
Currently, inputs have a margin-top of 1rem and selects have none. I would suggest removing the margin from the inputs as well. Setting appropriate margins depending on where the elements are used is better left to the individual users, I think.

**Comment by pschaub** [comment]
I agree with this. We removed the additional margin in our application code by overriding the CSS. In most cases, we define the margin between form elements through our own margin utility classes to keep it consistent.
