### ISSUE TITLE
bug: Little house icon next to logo in Breadcrumb Navigation after update

### ISSUE THREAD

**Issue by Kogs** [db-ui/core#620]
After updating db-ui-core to the newest Version (https://github.com/db-ui/core/compare/v2.12.2...v2.13.2)

A strange Home icon appeared next to our DB Logo.
![image](https://github.com/db-ui/core/assets/15261920/d1f2a70a-f37a-455d-ada5-cded952e8f93)

Dom looks like this:
```html
<nav aria-label="Breadcrumb" id="mainnavigation" class="cmp-breadcrumb">
  <ol>
    <li>
      <div class="cmp-brand">
        <a rel="home" title="Startseite" href="/">
          <img src="./images/db_logo.svg" alt="Logo" class="elm-image is-logo">
          <span id="app-name" class="is-site-name elm-link">Application Title</span>
        </a>
      </div>
    </li>
  </ol>
</nav>
```

We fixed it for now by defining this css rule in our own css files:
```css
.cmp-breadcrumb ol > *:first-child::before {
  content: "";
}

```

**Comment by mfranzke** [comment]
Hi @Kogs, thanks a lot for reaching out.

I'm not sure why this would have appeared through this update, but in general, is there a reason why you're using the breadcrumb in there at the logo?
The easiest solution would be to remove that `nav`, `ol` and `li` part so that only the following remains:
```html
      <div class="cmp-brand">
        <a rel="home" title="Startseite" href="/">
          <img src="./images/db_logo.svg" alt="Logo" class="elm-image is-logo">
          <span id="app-name" class="is-site-name elm-link">Application Title</span>
        </a>
      </div>
```

**Comment by Kogs** [comment]
Hello, yes our implementation is based on the reference implementation. The reason why the problem now occurred was because the css role was 
```css
.cmp-breadcrumb ol > *:first-child::before {
  --icon-glyph: '';
}
```
Changing --icon-glyph to content solves the issue.
