### ISSUE TITLE
Missing tab component documentation

### ISSUE THREAD

**Issue by d-koppenhagen** [db-ui/core#631]
As DB UI Elements wraps DB UI Core in Web Components and there is a Tab example, the base should be already available (See: https://db-ui.github.io/elements/?path=/story/02-navigation-tab-bar-intro--page).
The documentation should include the tab example in DB UI Core as well.

**Comment by mfranzke** [comment]
> As DB UI Elements wraps DB UI Core in Web Components and there is a Tab example, the base should be already available (See: https://db-ui.github.io/elements/?path=/story/02-navigation-tab-bar-intro--page). The documentation should include the tab example in DB UI Core as well.

@d-koppenhagen where & when do you get all of your inspiration from ?
