### ISSUE TITLE
Icons show up as Emojis

### ISSUE THREAD

**Issue by dinariox** [db-ui/core#823]
Hi, we use the db-ui core in our angular application. We have noticed a few times that the icons are sometimes displayed as Emojis rather than the actual icon. A refresh of the page seems to fix it. The problem is that we can't reproduce it reliably. We just have a few screenshots of it happening:

![Image](https://github.com/db-ui/core/assets/29123311/f0838645-4f4a-4c96-b905-492e23896f03)
![Image (1)](https://github.com/db-ui/core/assets/29123311/888d8f8e-0859-4868-9e81-9ccb921011dd)

This is how it is supposed to look:
<img width="497" alt="Bildschirmfoto 2024-04-24 um 12 47 30" src="https://github.com/db-ui/core/assets/29123311/12d3a7f3-6983-4b1b-862b-5b4bd4ac22ce">
This is also how it looks 99% of the time. We only had this issue a few times so far and cannot replicate it, though we are pretty sure that it only happened in Safari (mobile and desktop). We have found this article: https://css-tricks.com/text-that-sometimes-turns-to-emojis/
Not sure if it has anything to do with that. 

Our assumption was that the font sometimes simply did not load properly and therefore emojis were displayed instead of icons. However, we tried to serve our application with the font missing, which resulted in nothing being displayed in place of the icon. We have never been able to reproduce an emoji appearing.

The application is an Angular 17 app forked from the RI-Angular repo on GitLab (https://git.tech.rz.db.de/db-inner-source/tt-web/referenzimplementierungen/ri-angular).

We know that unfortunately we can't give you many clues and we don't expect you to know exactly what the problem is. However, we wanted to open an issue in case anyone has had the same problem.

Thanks in advance

**Comment by mfranzke** [comment]
@dinariox thanks a lot for reporting this. Actually you're already on the correct track – it's WebKit not being able to either load, or process the fonts under specific circumstances and that for the underlaying glyphs would get displayed (on other websites, these might even be rectangles), comparable (not visually, but conceptually) to what you would get on case of images that wouldn't be possible to get loaded (displaying broken images instead).

Unfortunately I'm not aware of any solution for this, not just as it only occurs occasionally, but as well only on WebKit, but also I don't see any possibility to detect this problem and interfere in these cases. The only other possibility would be to insert the icons into the source code directly, but that actually bloats the DOM with unnecessary elements on the other hand.

**Comment by dinariox** [comment]
@mfranzke thank you for the reply. Good to hear that it's really a Safari-only problem which is technically not allowed to use at DB so it isn't that big of an issue. It's a bummer that there's no easy fix but good to know that you're aware!
