### ISSUE TITLE
Deprecation warning for `inset-area` in Chrome

### ISSUE THREAD

**Issue by juthilo** [db-ui/core#981]
I noticed a deprecation warning in DevTools Console for the property `inset-area`, to be replaced by `position-area` (already supported in latest Chrome). Source is the [counter styling in _form-elements.scss](https://github.com/db-ui/core/blob/main/source/_patterns/01-elements/_form-elements.scss#L118-L122).

There is no timeframe on the removal from Chrome, just the vague but worrying "very soon". 😄 From [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/position-area): "This property was originally named and supported in Chromium browsers as inset-area, with the same property values. Both property names will be supported for a short while, for backwards compatibility purposes."

**Comment by mfranzke** [comment]
the fix will be released shortly with release v3.2.4
